// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;

#nullable disable

namespace MyApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113043234_BulkSeedData")]
    partial class BulkSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fashion"
                        });
                });

            modelBuilder.Entity("MyApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Name = "Product 1",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Name = "Product 2",
                            Price = 20.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Product 3",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Product 4",
                            Price = 30.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Product 5",
                            Price = 35.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Product 6",
                            Price = 40.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Product 7",
                            Price = 45.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Product 8",
                            Price = 50.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Name = "Product 9",
                            Price = 55.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Product 10",
                            Price = 60.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "Product 11",
                            Price = 65.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Name = "Product 12",
                            Price = 70.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Product 13",
                            Price = 75.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "Product 14",
                            Price = 80.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Name = "Product 15",
                            Price = 85.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Name = "Product 16",
                            Price = 90.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Name = "Product 17",
                            Price = 95.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Name = "Product 18",
                            Price = 100.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Name = "Product 19",
                            Price = 105.99m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Name = "Product 20",
                            Price = 110.99m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Name = "Product 21",
                            Price = 115.99m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Name = "Product 22",
                            Price = 120.99m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Name = "Product 23",
                            Price = 125.99m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Name = "Product 24",
                            Price = 130.99m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Name = "Product 25",
                            Price = 135.99m
                        });
                });

            modelBuilder.Entity("MyApp.Models.Product", b =>
                {
                    b.HasOne("MyApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
