// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;

#nullable disable

namespace MyApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113052923_AddProductData")]
    partial class AddProductData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("MyApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "iPhone 15",
                            Price = -50m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Gaming Laptop",
                            Price = 1450.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Bluetooth Speaker",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Office Chair",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Standing Desk",
                            Price = 450.75m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Coffee Table",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Leather Wallet",
                            Price = 35.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Backpack",
                            Price = 75.50m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Sunglasses",
                            Price = 150.00m
                        });
                });

            modelBuilder.Entity("MyApp.Models.Product", b =>
                {
                    b.HasOne("MyApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
